namespace SharpMetal.Enums
{
    public enum MTLVertexFormat: long
    {
        MTLVertexFormatInvalid = 0,
        MTLVertexFormatUChar = 45,
        MTLVertexFormatUChar2 = 1,
        MTLVertexFormatUChar3 = 2,
        MTLVertexFormatUChar4 = 3,
        MTLVertexFormatChar = 46,
        MTLVertexFormatChar2 = 4,
        MTLVertexFormatChar3 = 5,
        MTLVertexFormatChar4 = 6,
        MTLVertexFormatUCharNormalized = 47,
        MTLVertexFormatUChar2Normalized = 7,
        MTLVertexFormatUChar3Normalized = 8,
        MTLVertexFormatUChar4Normalized = 9,
        MTLVertexFormatCharNormalized = 48,
        MTLVertexFormatChar2Normalized = 10,
        MTLVertexFormatChar3Normalized = 11,
        MTLVertexFormatChar4Normalized = 12,
        MTLVertexFormatUShort = 49,
        MTLVertexFormatUShort2 = 13,
        MTLVertexFormatUShort3 = 14,
        MTLVertexFormatUShort4 = 15,
        MTLVertexFormatShort = 50,
        MTLVertexFormatShort2 = 16,
        MTLVertexFormatShort3 = 17,
        MTLVertexFormatShort4 = 18,
        MTLVertexFormatUShortNormalized = 51,
        MTLVertexFormatUShort2Normalized = 19,
        MTLVertexFormatUShort3Normalized = 20,
        MTLVertexFormatUShort4Normalized = 21,
        MTLVertexFormatShortNormalized = 52,
        MTLVertexFormatShort2Normalized = 22,
        MTLVertexFormatShort3Normalized = 23,
        MTLVertexFormatShort4Normalized = 24,
        MTLVertexFormatHalf = 53,
        MTLVertexFormatHalf2 = 25,
        MTLVertexFormatHalf3 = 26,
        MTLVertexFormatHalf4 = 27,
        MTLVertexFormatFloat = 28,
        MTLVertexFormatFloat2 = 29,
        MTLVertexFormatFloat3 = 30,
        MTLVertexFormatFloat4 = 31,
        MTLVertexFormatUInt = 36,
        MTLVertexFormatUInt2 = 37,
        MTLVertexFormatUInt3 = 38,
        MTLVertexFormatUInt4 = 39,
        MTLVertexFormatInt = 32,
        MTLVertexFormatInt2 = 33,
        MTLVertexFormatInt3 = 34,
        MTLVertexFormatInt4 = 35,
        MTLVertexFormatInt1010102Normalized = 40,
        MTLVertexFormatUInt1010102Normalized = 41,
        MTLVertexFormatUChar4Normalized_BGRA = 42
    }
}