name: Format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: write
  checks: write

concurrency:
  group: format-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - run: dotnet restore
      - name: Format
        run: dotnet format --verify-no-changes --report ./report.json -v d
      - name: Upload report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-format
          path: ./report.json
  build:
    uses: ./.github/workflows/build.yml
    needs: format
    secrets: inherit
